const list = [
    {
      id: 1,
      nom: "Soupe Legume",
      description: "lorem ipsum dolor sit amet",
      prix: 20000,
      img: "/src/image/Burger.png",
      amount: 1,
    },
    {
      id: 2,
      nom: "Soupe Legume",
      description: "lorem ipsum dolor sit amet",
      prix: 20000,
      img: "/src/image/Pizzaimage.jpg",
      amount: 1,
    },
    {
      id: 3,
      nom: "Soupe Legume",
      description: "lorem ipsum dolor sit amet",
      prix: 20000,
      img: "/src/image/imgCrudité.jpeg",
      amount: 1,
    },
    {
      id: 4,
      nom: "Soupe Legume",
      description: "lorem ipsum dolor sit amet",
      prix: 20000,
      img: "/src/image/Bolonaise.jpg",
      amount: 1,
    },
    {
      id: 5,
      nom: "Soupe Legume",
      description: "lorem ipsum dolor sit amet",
      prix: 20000,
      img: "/src/image/Bolonaise.jpg",
      amount: 1,
    },
    {
      id: 6,
      nom: "Soupe Legume",
      description: "lorem ipsum dolor sit amet",
      prix: 20000,
      img: "/src/image/Bolonaise.jpg",
      amount: 1,
    },
    {
      id: 7,
      nom: "Soupe Legume",
      description: "lorem ipsum dolor sit amet",
      prix: 20000,
      img: "/src/image/Bolonaise.jpg",
      amount: 1,
    },
    {
      id: 8,
      nom: "Soupe Legume",
      description: "lorem ipsum dolor sit amet",
      prix: 20000,
      img: "/src/image/Bolonaise.jpg",
      amount: 1,
    },
    {
      id: 9,
      nom: "Soupe Legume ",
      description: "lorem ipsum dolor sit amet",
      prix: 8200000,
      img: "/src/image/Bolonaise.jpg",
      amount: 1,
    },
    {
      id: 10,
      nom: "Soupe Legume",
      description: "lorem ipsum dolor sit amet",
      prix: 20000,
      img: "/src/image/Bolonaise.jpg",
      amount: 1,
    },
    {
      id: 11,
      nom: "Soupe Legume",
      description: "lorem ipsum dolor sit amet",
      prix: 20000,
      img: "/src/image/Bolonaise.jpg",
      amount: 1,
    },
    {
      id: 12,
      nom: "Soupe Legume",
      description: "lorem ipsum dolor sit amet",
      prix: 20000,
      img: "/src/image/Bolonaise.jpg",
      amount: 1,
    },
    
];

export default list;